-- Persistent, replayable state for BM Loop Engineering.
-- Service-role Netlify functions write these tables. RLS stays enabled so
-- clients cannot mutate loop state directly.

create table if not exists bm_loop_runs (
  loop_id text primary key,
  anonymous_user_id text not null,
  run_id text,
  trace_id text,
  recommendation_id text,
  schema_version integer not null default 1,
  contract_version text not null,
  loop_version text not null,
  status text not null,
  phase text not null,
  state_version integer not null default 0,
  event_sequence integer not null default 0,
  idempotency_key text not null,
  goal text not null,
  hypothesis text not null,
  trigger text not null,
  intervention jsonb not null default '{}',
  success_criteria jsonb not null default '{}',
  stop_conditions jsonb not null default '[]',
  budget jsonb not null default '{}',
  consent jsonb not null default '{}',
  verification jsonb not null default '{}',
  behavioral_outcome jsonb not null default '{}',
  adaptation jsonb not null default '{}',
  current_state jsonb not null default '{}',
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bm_loop_runs_status_check
    check (status in ('awaiting_input', 'awaiting_setup', 'awaiting_confirmation', 'awaiting_execution', 'retryable', 'completed', 'stopped', 'failed')),
  constraint bm_loop_runs_state_version_check
    check (state_version >= 0),
  constraint bm_loop_runs_event_sequence_check
    check (event_sequence >= 0)
);

create unique index if not exists bm_loop_runs_user_idempotency_idx
  on bm_loop_runs(anonymous_user_id, idempotency_key);

create index if not exists bm_loop_runs_user_updated_idx
  on bm_loop_runs(anonymous_user_id, updated_at desc);

create index if not exists bm_loop_runs_status_idx
  on bm_loop_runs(status, updated_at desc);

create table if not exists bm_loop_events (
  id bigint generated by default as identity primary key,
  loop_id text not null references bm_loop_runs(loop_id) on delete cascade,
  anonymous_user_id text not null,
  event_id text not null,
  event_sequence integer not null,
  event_type text not null,
  transition text not null,
  event_payload jsonb not null default '{}',
  created_at timestamptz not null default now(),
  unique (loop_id, event_id),
  unique (loop_id, event_sequence)
);

create index if not exists bm_loop_events_user_created_idx
  on bm_loop_events(anonymous_user_id, created_at desc);

create index if not exists bm_loop_events_loop_sequence_idx
  on bm_loop_events(loop_id, event_sequence);

alter table bm_loop_runs add column if not exists run_id text;
alter table bm_loop_runs add column if not exists trace_id text;
alter table bm_loop_runs add column if not exists schema_version integer not null default 1;

alter table bm_loop_runs enable row level security;
alter table bm_loop_events enable row level security;

create or replace function bm_append_loop_event(
  p_loop_id text,
  p_anonymous_user_id text,
  p_expected_state_version integer,
  p_transition text,
  p_event_id text,
  p_event_type text,
  p_event_payload jsonb,
  p_next_state jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  run_exists boolean;
  current_version integer;
  existing_state jsonb;
  next_state_version integer;
  next_event_sequence integer;
begin
  if p_loop_id is null or p_anonymous_user_id is null or p_event_id is null then
    raise exception 'missing_loop_identity';
  end if;

  select state_version, current_state
    into current_version, existing_state
    from bm_loop_runs
   where loop_id = p_loop_id
     and anonymous_user_id = p_anonymous_user_id
   for update;

  run_exists := found;

  if run_exists then
    if exists (
      select 1 from bm_loop_events
       where loop_id = p_loop_id and event_id = p_event_id
    ) then
      if exists (
        select 1 from bm_loop_events
         where loop_id = p_loop_id
           and event_id = p_event_id
           and event_payload = coalesce(p_event_payload, '{}'::jsonb)
      ) then
        return jsonb_build_object('status', 'duplicate', 'state', existing_state);
      end if;
      return jsonb_build_object('status', 'conflict', 'reason', 'event_id_payload_conflict', 'state', existing_state);
    end if;

    if current_version <> p_expected_state_version then
      return jsonb_build_object('status', 'conflict', 'state_version', current_version, 'state', existing_state);
    end if;
  elsif p_expected_state_version <> 0 then
    return jsonb_build_object('status', 'conflict', 'reason', 'missing_loop');
  end if;

  next_state_version := coalesce((p_next_state->>'state_version')::integer, p_expected_state_version + 1);
  next_event_sequence := coalesce((p_next_state->>'event_sequence')::integer, next_state_version);

  if not run_exists then
    insert into bm_loop_runs (
      loop_id, anonymous_user_id, run_id, trace_id, recommendation_id, schema_version, contract_version, loop_version,
      status, phase, state_version, event_sequence, idempotency_key, goal, hypothesis,
      trigger, intervention, success_criteria, stop_conditions, budget, consent,
      verification, behavioral_outcome, adaptation, current_state, expires_at
    ) values (
      p_loop_id,
      p_anonymous_user_id,
      nullif(p_next_state->>'run_id', ''),
      nullif(p_next_state->>'trace_id', ''),
      nullif(p_next_state->>'recommendation_id', ''),
      coalesce((p_next_state->>'schema_version')::integer, 1),
      p_next_state->>'contract_version',
      p_next_state->>'loop_version',
      p_next_state->>'status',
      p_next_state->>'phase',
      next_state_version,
      next_event_sequence,
      p_next_state->>'idempotency_key',
      p_next_state->>'goal',
      p_next_state->>'hypothesis',
      p_next_state->>'trigger',
      coalesce(p_next_state->'intervention', '{}'::jsonb),
      coalesce(p_next_state->'success_criteria', '{}'::jsonb),
      coalesce(p_next_state->'stop_conditions', '[]'::jsonb),
      coalesce(p_next_state->'budget', '{}'::jsonb),
      coalesce(p_next_state->'consent', '{}'::jsonb),
      coalesce(p_next_state->'verification', '{}'::jsonb),
      coalesce(p_next_state->'behavioral_outcome', '{}'::jsonb),
      coalesce(p_next_state->'adaptation', '{}'::jsonb),
      coalesce(p_next_state->'current_state', '{}'::jsonb),
      nullif(p_next_state->>'expires_at', '')::timestamptz
    );
  else
    update bm_loop_runs
       set run_id = nullif(p_next_state->>'run_id', ''),
           trace_id = nullif(p_next_state->>'trace_id', ''),
           recommendation_id = nullif(p_next_state->>'recommendation_id', ''),
           schema_version = coalesce((p_next_state->>'schema_version')::integer, schema_version),
           contract_version = coalesce(p_next_state->>'contract_version', contract_version),
           loop_version = coalesce(p_next_state->>'loop_version', loop_version),
           status = p_next_state->>'status',
           phase = p_next_state->>'phase',
           state_version = next_state_version,
           event_sequence = next_event_sequence,
           idempotency_key = coalesce(p_next_state->>'idempotency_key', idempotency_key),
           goal = coalesce(p_next_state->>'goal', goal),
           hypothesis = coalesce(p_next_state->>'hypothesis', hypothesis),
           trigger = coalesce(p_next_state->>'trigger', trigger),
           intervention = coalesce(p_next_state->'intervention', intervention),
           success_criteria = coalesce(p_next_state->'success_criteria', success_criteria),
           stop_conditions = coalesce(p_next_state->'stop_conditions', stop_conditions),
           budget = coalesce(p_next_state->'budget', budget),
           consent = coalesce(p_next_state->'consent', consent),
           verification = coalesce(p_next_state->'verification', verification),
           behavioral_outcome = coalesce(p_next_state->'behavioral_outcome', behavioral_outcome),
           adaptation = coalesce(p_next_state->'adaptation', adaptation),
           current_state = coalesce(p_next_state->'current_state', current_state),
           updated_at = now(),
           expires_at = nullif(p_next_state->>'expires_at', '')::timestamptz
     where loop_id = p_loop_id
       and anonymous_user_id = p_anonymous_user_id;
  end if;

  insert into bm_loop_events (
    loop_id, anonymous_user_id, event_id, event_sequence, event_type, transition, event_payload
  ) values (
    p_loop_id, p_anonymous_user_id, p_event_id, next_event_sequence, p_event_type, p_transition,
    coalesce(p_event_payload, '{}'::jsonb)
  );

  return jsonb_build_object('status', 'applied', 'state_version', next_state_version, 'event_sequence', next_event_sequence);
exception
  when unique_violation then
    if exists (
      select 1 from bm_loop_events
       where loop_id = p_loop_id and event_id = p_event_id
    ) then
      if exists (
        select 1 from bm_loop_events
         where loop_id = p_loop_id
           and event_id = p_event_id
           and event_payload = coalesce(p_event_payload, '{}'::jsonb)
      ) then
        return jsonb_build_object('status', 'duplicate');
      end if;
      return jsonb_build_object('status', 'conflict', 'reason', 'event_id_payload_conflict');
    end if;
    raise;
end;
$$;

revoke all on function bm_append_loop_event(text, text, integer, text, text, text, jsonb, jsonb) from public;

create or replace view bm_loop_learning_summary as
select
  goal,
  count(*) as loop_count,
  count(*) filter (where status = 'completed') as completed_count,
  count(*) filter (where status = 'failed') as failed_count,
  count(*) filter (where behavioral_outcome->>'status' = 'improved') as improved_outcome_count,
  count(*) filter (where behavioral_outcome->>'status' = 'held') as held_outcome_count,
  count(*) filter (where behavioral_outcome->>'status' = 'relapse') as relapse_outcome_count,
  round(avg(nullif(behavioral_outcome->>'score', '')::numeric) filter (where behavioral_outcome->>'score' is not null), 2) as average_outcome_score,
  max(updated_at) as last_updated_at
from bm_loop_runs
group by goal;
